language: rust
sudo: true
cache:
    apt: true
    cargo: true
rust:
    - nightly
addons:
  apt:
    packages:
    - gcc
    - g++
before_install:
    - git clone -b stable https://github.com/jedisct1/libsodium.git
    - cd libsodium && sudo ./configure && sudo make check && sudo make install && cd ..
env:
    - LD_LIBRARY_PATH=${HOME}/libsodium/lib
    - PKG_CONFIG_PATH=${HOME}/libsodium/lib/pkgconfig
    - LDFLAGS="-L${HOME}/libsodium/lib"
script:
    - cargo build
    - cargo test
    - cargo doc --no-deps
    #- cargo doc --no-deps -p oni_simulator

#matrix:
#  allow_failures:
#    - rust: nightly
#  fast_finish: true
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    #keep-history: true
    local-dir: target/doc
    on:
        branch: master
