language: rust
cache: cargo
rust:
    - nightly
script:
    - cargo build --all --exclude relay
    - cargo test --all --exclude relay
    - cargo doc --all --exclude relay --no-deps
#matrix:
#  allow_failures:
#    - rust: nightly
#  fast_finish: true
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    #keep-history: true
    local-dir: target/doc
    on:
        branch: master
