language: rust
cache: cargo
rust:
    - nightly
script:
    - cargo build
    - cargo test
    - cargo doc --no-deps
    - cargo doc --no-deps -p oni_simulator
#matrix:
#  allow_failures:
#    - rust: nightly
#  fast_finish: true
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    #keep-history: true
    local-dir: target/doc
    on:
        branch: master
