language: rust
sudo: true
cache:
    apt: true
    cargo: true
    directories:
    - $HOME/libsodium
rust:
    - nightly
addons:
  apt:
    packages:
    - gcc
    - g++
before_install:
    - ./travis-libsodium.sh
script:
    - ./travis-build.sh
#matrix:
#  allow_failures:
#    - rust: nightly
#  fast_finish: true
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    #keep-history: true
    local-dir: target/doc
    on:
        branch: master
