[package]
name = "relay"
version = "0.1.0"
authors = ["Lain-dono <lain.dono@gmail.com>"]
edition = "2018"

[dependencies]
oni = { path = "../.." }
rocket = { version = "0.3.17", features = ["tls"] }
rocket_codegen = "0.3.17"
