cargo-features = ["edition"]

[package]
name = "oni_net"
version = "0.1.0"
authors = ["Lain-dono <lain.dono@gmail.com>"]

edition = '2018'

[dependencies]
bitflags = "1"
byteorder = "1"
typenum = "1"
slotmap = "0.2.0"
generic-array = "0.11.1"

rand = "0.5.4"

env_logger = "*"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
