cargo-features = ["edition"]

[package]
name = "oni_simulator"
version = "0.1.0"
authors = ["Lain-dono <lain.dono@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.5"
generic-array = "0.11"
slotmap = "0.2"
