cargo-features = ["edition"]

[package]
name = "oni_reliable"
version = "0.1.0"
authors = ["Lain-dono <lain.dono@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
generic-array = "0.11.1"
byteorder = "1"
