(function() {var implementors = {};
implementors["oni"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a>&gt; for <a class=\"type\" href=\"oni/bitset/type.BitSet8.html\" title=\"type oni::bitset::BitSet8\">BitSet8</a>",synthetic:false,types:["oni::bitset::BitSet8"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u16.html\">u16</a>&gt; for <a class=\"type\" href=\"oni/bitset/type.BitSet16.html\" title=\"type oni::bitset::BitSet16\">BitSet16</a>",synthetic:false,types:["oni::bitset::BitSet16"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u32.html\">u32</a>&gt; for <a class=\"type\" href=\"oni/bitset/type.BitSet32.html\" title=\"type oni::bitset::BitSet32\">BitSet32</a>",synthetic:false,types:["oni::bitset::BitSet32"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u64.html\">u64</a>&gt; for <a class=\"type\" href=\"oni/bitset/type.BitSet64.html\" title=\"type oni::bitset::BitSet64\">BitSet64</a>",synthetic:false,types:["oni::bitset::BitSet64"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u128.html\">u128</a>&gt; for <a class=\"type\" href=\"oni/bitset/type.BitSet128.html\" title=\"type oni::bitset::BitSet128\">BitSet128</a>",synthetic:false,types:["oni::bitset::BitSet128"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
