(function() {var implementors = {};
implementors["oni"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"oni/enum.ConnectingState.html\" title=\"enum oni::ConnectingState\">ConnectingState</a>",synthetic:false,types:["oni::client::ConnectingState"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"oni/enum.Error.html\" title=\"enum oni::Error\">Error</a>",synthetic:false,types:["oni::client::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"oni/enum.State.html\" title=\"enum oni::State\">State</a>",synthetic:false,types:["oni::client::State"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"oni/struct.SimulatorConfig.html\" title=\"struct oni::SimulatorConfig\">SimulatorConfig</a>",synthetic:false,types:["oni::simulator::SimulatorConfig"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"oni/protocol/struct.Request.html\" title=\"struct oni::protocol::Request\">Request</a>",synthetic:false,types:["oni::protocol::Request"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"oni/protocol/enum.Packet.html\" title=\"enum oni::protocol::Packet\">Packet</a>&lt;'a&gt;",synthetic:false,types:["oni::protocol::Packet"]},];
implementors["oni_simulator"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"oni_simulator/struct.Config.html\" title=\"struct oni_simulator::Config\">Config</a>",synthetic:false,types:["oni_simulator::config::Config"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
